In [3]:
import pandas as pd

pd.read_parquet("../CRYPTO_DAILY_DATA/BTCUSDT/2025-01-02.parquet")

,Open_time,Open,High,Low,Close,Volume,Close_time,Quote_asset_volume,Number_of_trades,Taker_buy_base_asset_volume,Taker_buy_quote_asset_volume,Ignore
0,1735776000000000,94591.78,94591.79,94591.78,94591.79,0.12408,1735776000999999,11736.948500,20,0.04380,4143.120402,0
1,1735776001000000,94591.79,94591.79,94591.78,94591.79,0.04734,1735776001999999,4477.974929,7,0.00639,604.441538,0
2,1735776002000000,94591.78,94591.79,94591.78,94591.79,0.09190,1735776002999999,8692.985006,7,0.04235,4005.962307,0
3,1735776003000000,94591.78,94591.79,94591.78,94591.79,0.03234,1735776003999999,3059.098464,7,0.02985,2823.564932,0
4,1735776004000000,94591.79,94591.79,94591.79,94591.79,0.01300,1735776004999999,1229.693270,5,0.01300,1229.693270,0
...,...,...,...,...,...,...,...,...,...,...,...,...
86395,1735862395000000,96984.79,96984.79,96984.78,96984.78,0.06427,1735862395999999,6233.211851,2,0.00403,390.848704,0
86396,1735862396000000,96984.79,96984.79,96984.79,96984.79,0.00291,1735862396999999,282.225739,5,0.00291,282.225739,0
86397,1735862397000000,96984.79,96984.79,96984.79,96984.79,0.33986,1735862397999999,32961.250729,18,0.33986,32961.250729,0
86398,1735862398000000,96984.79,96984.79,96984.79,96984.79,0.00350,1735862398999999,339.446765,6,0.00350,339.446765,0
86399,1735862399000000,96984.79,96984.79,96984.79,96984.79,0.00116,1735862399999999,112.502356,2,0.00116,112.502356,0